const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {create,KEY}=require('../src/campaign.js');
let clock=1000,mem={};const storage={getItem:k=>mem[k]||null,setItem:(k,v)=>mem[k]=v};
const api=create(storage,()=>clock);api.read();const initial=api.read();
const remote={...initial,done:[1,2],coins:876,inventory:{hammer:4,shuffle:5,fan:6},updatedAt:2000,active:{id:8}};
api.restore(remote);assert.equal(api.read().coins,876);assert.equal(api.unlocked(),3);assert.equal(api.read().active,null);
clock=3000;api.buy('hammer');api.restore(remote);assert.equal(api.read().coins,626);assert.equal(api.read().inventory.hammer,5);
api.restore({version:1,coins:999});assert.equal(api.read().coins,626);
const handlers={},scene={events:{once(){}},input:{enabled:true},time:{paused:false},tweens:{pauseAll(){this.paused=true},resumeAll(){this.paused=false}},music:{pause(v){this.paused=v}},fx:{stopAll(){this.stopped=true}}};
let stops=0,starts=0,time=0,timers=[];
const lifecycleContext={Set,Map,Promise,performance:{now:()=>time},setTimeout:f=>timers.push(f),document:{hidden:false,addEventListener:(e,f)=>handlers[e]=f},window:{addEventListener:(e,f)=>handlers[e]=f,BerriesYandex:{gameplayStop(){stops++},gameplayStart(){starts++}},__berriesGameplayShouldRun:true}};
vm.runInNewContext(fs.readFileSync('src/lifecycle.js','utf8'),lifecycleContext);
const life=lifecycleContext.window.BerriesLifecycle;life.register(scene);life.set('ad',true);life.set('hidden',true);life.set('ad',false);
assert(life.paused);assert.equal(scene.input.enabled,false);assert(scene.time.paused);assert(scene.tweens.paused);assert(scene.fx.stopped);
life.set('hidden',false);assert(!life.paused);assert(scene.input.enabled);assert(!scene.time.paused);assert.equal(stops,1);assert.equal(starts,1);
(async()=>{
 let resolved=false;const wait=life.wait(100).then(()=>resolved=true);life.set('ad',true);time=200;timers.shift()();await Promise.resolve();assert(!resolved);life.set('ad',false);time=301;timers.shift()();await wait;assert(resolved);
 let adOptions,adCalls=0,writes=0,restoreCalls=0,readFails=false,reasons=new Set();
 const platform={environment:{i18n:{lang:'de'}},on(){},getPlayer:async()=>({getData:async()=>{if(readFails)throw Error('offline');return{berries:remote}},setData:async()=>writes++}),adv:{showRewardedVideo:o=>{adCalls++;adOptions=o}},features:{GameplayAPI:{start(){},stop(){}},LoadingAPI:{ready(){}}}};
 const sdkContext={console:{warn(){}},setTimeout:()=>1,clearTimeout(){},JSON,navigator:{language:'en'},document:{addEventListener(){}},window:{addEventListener(){},YaGames:{init:async()=>platform},BerriesLifecycle:{set:(r,v)=>v?reasons.add(r):reasons.delete(r),get paused(){return reasons.size>0}},BerriesCampaign:{restore(){restoreCalls++},read:()=>initial}}};
 vm.runInNewContext(fs.readFileSync('src/sdk/yandex.js','utf8'),sdkContext);const sdk=sdkContext.window.BerriesYandex;
 assert.equal(sdk.saveCloudData(initial),false);await sdk.restoreCampaign();assert.equal(restoreCalls,1);await sdk.flushCloud();assert.equal(writes,1);assert.equal(sdk.language.current,'ru');assert.equal(sdk.language.detected,'de');
 let a=sdk.showRewardedVideo(),b=sdk.showRewardedVideo();assert.equal(a,b);for(let i=0;i<8;i++)await Promise.resolve();assert.equal(adCalls,1);assert(reasons.has('advertisement'));adOptions.callbacks.onClose();assert.equal(await a,false);assert(!reasons.size);
 a=sdk.showRewardedVideo();for(let i=0;i<8;i++)await Promise.resolve();adOptions.callbacks.onRewarded();adOptions.callbacks.onClose();assert.equal(await a,true);
 a=sdk.showRewardedVideo();for(let i=0;i<8;i++)await Promise.resolve();adOptions.callbacks.onError();assert.equal(await a,false);assert(!reasons.size);
 readFails=true;vm.runInNewContext(fs.readFileSync('src/sdk/yandex.js','utf8'),sdkContext);await sdkContext.window.BerriesYandex.restoreCampaign();assert.equal(sdkContext.window.BerriesYandex.saveCloudData(initial),false);
 const source=fs.readFileSync('src/vertical_slice.js','utf8');
 const Sfx=new Function('window','localStorage','performance',source.slice(source.indexOf('class Sfx'),source.indexOf('const MUSIC_TRACKS'))+';return Sfx')({BerriesLifecycle:life},storage,{now:()=>clock});
 let playing=0;const sndScene={events:{once(){}},cache:{audio:{exists:()=>true}},sound:{add:()=>({isPlaying:false,play(){this.isPlaying=true;playing++},stop(){this.isPlaying=false},destroy(){}})}};
 const fx=new Sfx(sndScene);fx.iceBreak();clock+=150;fx.iceBreak();assert.equal(playing,2);fx.muted=true;clock+=150;fx.iceBreak();assert.equal(playing,2);assert(new Sfx(sndScene).muted);
 fx.muted=false;life.set('ad',true);clock+=150;fx.iceBreak();assert.equal(playing,2);life.set('ad',false);
 console.log('PASS cloud snapshot restore, stale snapshot protection, nested pause, paused waits, rewarded once/cancel/error, failed cloud read protection');
})().catch(e=>{console.error(e);process.exitCode=1});
