(() => {
'use strict';
const W=1920,H=1080,R=8,C=8,CELL=96,BX=576,BY=178;
const TYPES=['strawberry','raspberry','blueberry','gooseberry','blackberry','cloudberry'];
const LV={
1:{m:18,n:5,g:[['berry','strawberry',12]],ice:[],ac:[],root:[]},
6:{m:18,n:6,g:[['score',null,900]],ice:[],ac:[],root:[]},
11:{m:20,n:6,g:[['ice',null,8]],ice:[[1,1,1],[1,6,1],[3,2,1],[3,5,1],[5,2,1],[5,5,1],[6,1,1],[6,6,1]],ac:[],root:[]},
16:{m:20,n:6,g:[['acorn',null,4]],ice:[],ac:[[2,2],[2,5],[5,2],[5,5]],root:[]},
21:{m:20,n:6,g:[['roots',null,8]],ice:[],ac:[],root:[[1,2],[1,5],[2,1],[2,6],[5,1],[5,6],[6,2],[6,5]]},
30:{m:24,n:6,g:[['ice',null,12],['acorn',null,4],['roots',null,6]],ice:[[0,1,1],[0,6,1],[1,0,1],[1,7,1],[3,3,2],[3,4,2],[4,3,2],[4,4,2],[6,0,1],[6,7,1],[7,1,1],[7,6,1]],ac:[[2,2],[2,5],[5,2],[5,5]],root:[[1,3],[1,4],[3,1],[4,6],[6,3],[6,4]]}
};
const KEY='berries_vs_02';
class Sfx{constructor(s){this.s=s}ctx(){return this.s.sound?.context}tone(f,d=.06,g=.02,t='sine',e=0){let c=this.ctx();if(!c)return;let n=c.currentTime,o=c.createOscillator(),a=c.createGain();o.type=t;o.frequency.setValueAtTime(f,n);if(e)o.frequency.exponentialRampToValueAtTime(Math.max(50,f+e),n+d);a.gain.setValueAtTime(.0001,n);a.gain.exponentialRampToValueAtTime(g,n+.006);a.gain.exponentialRampToValueAtTime(.0001,n+d);o.connect(a).connect(c.destination);o.start(n);o.stop(n+d+.02)}pop(p=1){this.tone(185*p,.055,.018,'sine',70)}click(){this.tone(520,.03,.012,'triangle',50)}bad(){this.tone(180,.08,.015,'triangle',-40)}crack(){this.tone(820,.04,.008,'square',-350);this.tone(390,.06,.008,'triangle',-120)}spark(){this.tone(900,.08,.009,'sine',350);setTimeout(()=>this.tone(1260,.06,.007,'sine',150),35)}win(){[523,659,784].forEach((f,i)=>setTimeout(()=>this.tone(f,.14,.015,'sine',120),i*85))}lose(){[392,330,262].forEach((f,i)=>setTimeout(()=>this.tone(f,.14,.012,'sine',-20),i*85))}}
class Boot extends Phaser.Scene{constructor(){super('Boot')}preload(){let t=this.add.text(W/2,H/2,'Загружаем лес…',{fontSize:'36px',color:'#fff7dc'}).setOrigin(.5);this.load.on('progress',v=>t.setText(`Загружаем лес… ${Math.round(v*100)}%`));let I=(k,p)=>this.load.image(k,p);I('title','assets/backgrounds/background_title_forest.jpg');I('gamebg','assets/backgrounds/background_game_forest.jpg');I('mapbg','assets/map/map_forest_background.jpg');I('logo','assets/ui/panels/logo_main.png');I('plevel','assets/ui/panels/panel_level_title.png');I('pgoals','assets/ui/panels/panel_goals.png');I('btn','assets/ui/buttons/button_wood.png');['normal','current','completed','locked'].forEach(x=>I('lvl_'+x,'assets/ui/buttons/level_'+x+'.png'));['idle','point','celebrate','sad'].forEach(x=>I('king_'+x,'assets/characters/king/king_'+x+'.png'));I('ice1','assets/blockers/blocker_ice_1.png');I('ice2','assets/blockers/blocker_ice_2.png');I('acorn','assets/blockers/goal_acorn.png');I('roots','assets/blockers/blocker_roots.png');I('line_h','assets/specials/special_line_h.png');I('line_v','assets/specials/special_line_v.png');I('rainbow','assets/specials/special_rainbow.png');TYPES.forEach(x=>I('b_'+x,'assets/berries/berry_'+x+'.png'))}create(){this.scene.start('Title')}}
class Title extends Phaser.Scene{constructor(){super('Title')}create(){this.add.image(W/2,H/2,'title').setDisplaySize(W,H);this.add.rectangle(W/2,H/2,W,H,0x07180d,.08);let l=this.add.image(W/2,350,'logo').setScale(.52);this.tweens.add({targets:l,y:365,duration:2100,yoyo:true,repeat:-1,ease:'Sine.inOut'});let c=this.add.container(W/2,810),b=this.add.image(0,0,'btn').setDisplaySize(360,132).setInteractive({useHandCursor:true}),tx=this.add.text(0,0,'ИГРАТЬ',{fontSize:'46px',fontStyle:'bold',color:'#ffe9a0',stroke:'#6b2e17',strokeThickness:8}).setOrigin(.5);c.add([b,tx]);b.on('pointerdown',()=>{this.tweens.add({targets:c,scale:.95,duration:80,yoyo:true});this.scene.start('Map')})}}
class Map extends Phaser.Scene{constructor(){super('Map')}create(){this.add.image(W/2,H/2,'mapbg').setDisplaySize(W,H);this.add.rectangle(W/2,H/2,W,H,0x06130b,.08);this.add.text(W/2,75,'ТЕСТОВАЯ КАРТА',{fontSize:'44px',fontStyle:'bold',color:'#fff1b0',stroke:'#542b15',strokeThickness:8}).setOrigin(.5);let sv={};try{sv=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}let done=new Set(sv.done||[]),a=[{n:1,x:360,y:760},{n:6,x:610,y:610},{n:11,x:860,y:735},{n:16,x:1110,y:545},{n:21,x:1370,y:670},{n:30,x:1580,y:410}];a.forEach(({n,x,y},i)=>{let k=done.has(n)?'lvl_completed':(i===0||done.has(a[i-1]?.n)?'lvl_current':'lvl_normal'),im=this.add.image(x,y,k).setDisplaySize(150,150).setInteractive({useHandCursor:true});this.add.text(x,y,String(n),{fontSize:'42px',fontStyle:'bold',color:'#fff4ca',stroke:'#5b2c14',strokeThickness:7}).setOrigin(.5);im.on('pointerdown',()=>this.scene.start('Play',{n}));this.tweens.add({targets:im,y:y-8,duration:1400+i*90,yoyo:true,repeat:-1,ease:'Sine.inOut'})});let k=this.add.image(1660,830,'king_point').setScale(.33);this.tweens.add({targets:k,y:812,duration:1700,yoyo:true,repeat:-1,ease:'Sine.inOut'})}}
class Play extends Phaser.Scene{constructor(){super('Play')}init(d){this.no=+d.n||1;this.cfg=LV[this.no]||LV[1]}create(){this.fx=new Sfx(this);this.moves=this.cfg.m;this.score=0;this.busy=false;this.sel=null;this.last=null;this.goals=this.cfg.g.map(x=>({type:x[0],id:x[1],need:x[2],done:0}));this.board=Array.from({length:R},()=>Array(C).fill(null));this.cell=Array.from({length:R},()=>Array.from({length:C},()=>({ice:0,block:null,over:null})));this.spr=Array.from({length:R},()=>Array(C).fill(null));this.add.image(W/2,H/2,'gamebg').setDisplaySize(W,H);this.add.rectangle(W/2,H/2,W,H,0x06140a,.12);this.hud();this.cfg.ice.forEach(([r,c,h])=>this.cell[r][c].ice=h);this.cfg.ac.forEach(([r,c])=>this.cell[r][c].block='acorn');this.cfg.root.forEach(([r,c])=>this.cell[r][c].block='roots');this.seed();this.drawAll(true);this.updateHud();this.kingAnim('idle')}
hud(){this.add.image(W/2,70,'plevel').setDisplaySize(540,120);this.add.text(W/2,68,`УРОВЕНЬ ${this.no}`,{fontSize:'44px',fontStyle:'bold',color:'#ffeeb0',stroke:'#622f17',strokeThickness:8}).setOrigin(.5);this.add.text(135,72,'←',{fontSize:'58px',fontStyle:'bold',color:'#fff5c7',stroke:'#4f2a15',strokeThickness:7}).setOrigin(.5).setInteractive({useHandCursor:true}).on('pointerdown',()=>this.scene.start('Map'));this.mt=this.add.text(1540,72,'',{fontSize:'34px',fontStyle:'bold',color:'#fff5cb',stroke:'#4e2b16',strokeThickness:6}).setOrigin(.5);this.st=this.add.text(1735,72,'',{fontSize:'27px',color:'#fff5cb',stroke:'#4e2b16',strokeThickness:5}).setOrigin(.5);this.add.image(300,430,'pgoals').setDisplaySize(430,560);this.add.text(300,220,'ЦЕЛИ',{fontSize:'38px',fontStyle:'bold',color:'#ffeaae',stroke:'#613117',strokeThickness:7}).setOrigin(.5);this.gt=this.goals.map((g,i)=>this.add.text(300,315+i*105,'',{fontSize:'27px',fontStyle:'bold',align:'center',color:'#fff4d5',stroke:'#4b2915',strokeThickness:5,wordWrap:{width:330}}).setOrigin(.5));this.king=this.add.image(1650,650,'king_idle').setScale(.36);let q=this.add.graphics();q.fillStyle(0x3b1e12,.72);q.fillRoundedRect(BX-28,BY-28,C*CELL+56,R*CELL+56,34);q.lineStyle(7,0xc88943,.85);q.strokeRoundedRect(BX-28,BY-28,C*CELL+56,R*CELL+56,34);for(let r=0;r<R;r++)for(let c=0;c<C;c++){q.fillStyle((r+c)%2?0x466b38:0x547943,.62);q.fillRoundedRect(BX+c*CELL+4,BY+r*CELL+4,CELL-8,CELL-8,16)}}
seed(){let a=TYPES.slice(0,this.cfg.n);for(let r=0;r<R;r++)for(let c=0;c<C;c++){if(this.cell[r][c].block)continue;let id,t=0;do{id=Phaser.Utils.Array.GetRandom(a);t++}while(t<30&&((c>1&&this.board[r][c-1]?.id===id&&this.board[r][c-2]?.id===id)||(r>1&&this.board[r-1][c]?.id===id&&this.board[r-2][c]?.id===id)));this.board[r][c]={id,sp:null}}if(!this.hasMove())this.shuffle()}
pos(r,c){return{x:BX+c*CELL+CELL/2,y:BY+r*CELL+CELL/2}}
render(r,c,first=false){let ce=this.cell[r][c],p=this.pos(r,c);if(this.spr[r][c])this.spr[r][c].destroy();if(ce.over)ce.over.destroy();this.spr[r][c]=null;ce.over=null;if(ce.block){this.spr[r][c]=this.add.image(p.x,p.y,ce.block).setDisplaySize(CELL*.84,CELL*.84).setDepth(4)}else if(this.board[r][c]){let it=this.board[r][c],im=this.add.image(p.x,p.y,it.sp?it.sp:'b_'+it.id).setDisplaySize(CELL*.82,CELL*.82).setDepth(3).setInteractive({useHandCursor:true});let sx=im.scaleX,sy=im.scaleY;im.setData({r,c,sx,sy});im.on('pointerdown',()=>this.tap(r,c));this.spr[r][c]=im;if(first){im.setScale(sx*.25,sy*.25);this.tweens.add({targets:im,scaleX:sx,scaleY:sy,duration:220+r*25,ease:'Back.out'})}}if(ce.ice)ce.over=this.add.image(p.x,p.y,ce.ice>1?'ice2':'ice1').setDisplaySize(CELL*.95,CELL*.95).setDepth(5).setAlpha(.82)}
drawAll(first=false){for(let r=0;r<R;r++)for(let c=0;c<C;c++)this.render(r,c,first)}
tap(r,c){if(this.busy||this.cell[r][c].block||!this.board[r][c])return;this.fx.click();if(!this.sel){this.select(r,c);return}if(this.sel.r===r&&this.sel.c===c){this.unselect();return}if(Math.abs(this.sel.r-r)+Math.abs(this.sel.c-c)!==1){this.unselect();this.select(r,c);return}let a={...this.sel};this.unselect();this.swap(a,{r,c})}
select(r,c){this.sel={r,c};let s=this.spr[r][c],sx=s.getData('sx'),sy=s.getData('sy');s.setTint(0xfff4c2);this.tweens.add({targets:s,scaleX:sx*1.08,scaleY:sy*1.08,duration:110,yoyo:true,repeat:-1,ease:'Sine.inOut'})}
unselect(){if(!this.sel)return;let s=this.spr[this.sel.r]?.[this.sel.c];if(s){this.tweens.killTweensOf(s);s.clearTint();s.setScale(s.getData('sx'),s.getData('sy'))}this.sel=null}
async swap(a,b){this.busy=true;this.last=b;let A=this.spr[a.r][a.c],B=this.spr[b.r][b.c];await Promise.all([this.move(A,b),this.move(B,a)]);this.swapData(a,b);let ok=this.groups().length>0;if(!ok){this.fx.bad();await Promise.all([this.move(A,a),this.move(B,b)]);this.swapData(a,b);this.busy=false;return}this.moves--;let t=this.spr[a.r][a.c];this.spr[a.r][a.c]=this.spr[b.r][b.c];this.spr[b.r][b.c]=t;await this.resolve();this.busy=false;this.updateHud();this.endCheck()}
move(s,p){if(!s)return Promise.resolve();let q=this.pos(p.r,p.c);return new Promise(z=>this.tweens.add({targets:s,x:q.x,y:q.y,duration:145,ease:'Sine.inOut',onComplete:z}))}
swapData(a,b){let t=this.board[a.r][a.c];this.board[a.r][a.c]=this.board[b.r][b.c];this.board[b.r][b.c]=t}
groups(){let out=[];for(let r=0;r<R;r++){let c=0;while(c<C){let x=this.board[r][c];if(!x){c++;continue}let e=c+1;while(e<C&&this.board[r][e]?.id===x.id)e++;if(e-c>=3)out.push({id:x.id,dir:'h',p:Array.from({length:e-c},(_,i)=>({r,c:c+i}))});c=e}}for(let c=0;c<C;c++){let r=0;while(r<R){let x=this.board[r][c];if(!x){r++;continue}let e=r+1;while(e<R&&this.board[e][c]?.id===x.id)e++;if(e-r>=3)out.push({id:x.id,dir:'v',p:Array.from({length:e-r},(_,i)=>({r:r+i,c}))});r=e}}return out}
async resolve(){let chain=0;while(true){let gs=this.groups();if(!gs.length)break;chain++;let clear=[],keep=new Set();for(let g of gs){let sp=g.p.length>=5?'rainbow':g.p.length===4?(g.dir==='h'?'line_h':'line_v'):null,at=sp?(g.p.find(p=>this.last&&p.r===this.last.r&&p.c===this.last.c)||g.p[Math.floor(g.p.length/2)]):null;if(at){keep.add(at.r+','+at.c);this.board[at.r][at.c]={id:g.id,sp}}g.p.forEach(p=>clear.push(p))}clear=this.uniq(clear).filter(p=>!keep.has(p.r+','+p.c));chain>=3?this.fx.spark():this.fx.pop(1+chain*.04);await this.clear(clear,chain);keep.forEach(k=>{let [r,c]=k.split(',').map(Number);this.render(r,c)});await this.drop()}if(!this.hasMove()){this.shuffle();this.drawAll();this.toast('Нет ходов — перемешиваем!')}}
async clear(ps,chain){let jobs=[],near=new Set();for(let p of ps){if(!this.ins(p.r,p.c))continue;let ce=this.cell[p.r][p.c];if(ce.ice){ce.ice--;this.goal('ice',1);this.fx.crack();if(ce.over){jobs.push(new Promise(z=>this.tweens.add({targets:ce.over,alpha:0,duration:120,onComplete:()=>{ce.over?.destroy();ce.over=null;z()}})))}}if(ce.block){this.hitBlock(p.r,p.c);continue}let it=this.board[p.r][p.c];if(!it)continue;this.goal('berry',1,it.id);this.score+=Math.round(50*Math.min(2,1+(chain-1)*.25));let s=this.spr[p.r][p.c];if(s){let sx=s.getData('sx'),sy=s.getData('sy');jobs.push(new Promise(z=>this.tweens.add({targets:s,scaleX:sx*1.25,scaleY:sy*.65,alpha:0,duration:125,onComplete:()=>{s.destroy();z()}})));this.spr[p.r][p.c]=null}this.board[p.r][p.c]=null;[[1,0],[-1,0],[0,1],[0,-1]].forEach(([dr,dc])=>{let r=p.r+dr,c=p.c+dc;if(this.ins(r,c)&&this.cell[r][c].block)near.add(r+','+c)})}near.forEach(k=>{let[r,c]=k.split(',').map(Number);this.hitBlock(r,c)});await Promise.all(jobs);this.updateHud()}
hitBlock(r,c){let ce=this.cell[r][c];if(!ce.block)return;let type=ce.block,s=this.spr[r][c];this.fx.crack();ce.block=null;this.goal(type==='acorn'?'acorn':'roots',1);if(s)this.tweens.add({targets:s,alpha:0,y:'-=18',duration:160,onComplete:()=>s.destroy()});this.spr[r][c]=null;this.board[r][c]=null}
async drop(){let a=TYPES.slice(0,this.cfg.n);for(let c=0;c<C;c++){let bot=R-1;while(bot>=0){while(bot>=0&&this.cell[bot][c].block)bot--;if(bot<0)break;let top=bot;while(top>0&&!this.cell[top-1][c].block)top--;let arr=[];for(let r=bot;r>=top;r--)if(this.board[r][c])arr.push(this.board[r][c]);let i=0;for(let r=bot;r>=top;r--)this.board[r][c]=i<arr.length?arr[i++]:null;for(let r=top;r<=bot;r++)if(!this.board[r][c])this.board[r][c]={id:Phaser.Utils.Array.GetRandom(a),sp:null};bot=top-1}}this.drawAll();await new Promise(z=>this.time.delayedCall(170,z))}
shuffle(){let a=TYPES.slice(0,this.cfg.n),t=0;do{for(let r=0;r<R;r++)for(let c=0;c<C;c++)if(!this.cell[r][c].block)this.board[r][c]={id:Phaser.Utils.Array.GetRandom(a),sp:null};t++}while((this.groups().length||!this.hasMove())&&t<50)}
hasMove(){for(let r=0;r<R;r++)for(let c=0;c<C;c++){if(!this.board[r][c])continue;for(let[d,e]of[[0,1],[1,0]]){let rr=r+d,cc=c+e;if(!this.ins(rr,cc)||!this.board[rr][cc])continue;this.swapData({r,c},{r:rr,c:cc});let ok=this.groups().length;this.swapData({r,c},{r:rr,c:cc});if(ok)return true}}return false}
goal(t,a,id=null){this.goals.forEach(g=>{if(g.type!==t)return;if(t==='berry'&&g.id!==id)return;g.done=Math.min(g.need,g.done+a)})}
done(){return this.goals.every(g=>g.type==='score'?this.score>=g.need:g.done>=g.need)}
updateHud(){this.mt.setText('ХОДЫ: '+this.moves);this.st.setText('СЧЁТ: '+this.score);let nm={berry:'Собрать ягоды',ice:'Разбить лёд',acorn:'Собрать жёлуди',roots:'Убрать корни',score:'Набрать очки'};this.goals.forEach((g,i)=>{let cur=g.type==='score'?this.score:g.done,lab=g.type==='berry'?'Собрать '+({strawberry:'клубнику',raspberry:'малину',blueberry:'чернику',gooseberry:'крыжовник',blackberry:'ежевику',cloudberry:'морошку'}[g.id]):nm[g.type];this.gt[i].setText(`${lab}\n${Math.min(cur,g.need)} / ${g.need}`)})}
endCheck(){if(this.done()){this.busy=true;this.save();this.fx.win();this.kingAnim('celebrate');this.time.delayedCall(550,()=>this.popup(true))}else if(this.moves<=0){this.busy=true;this.fx.lose();this.kingAnim('sad');this.time.delayedCall(450,()=>this.popup(false))}}
popup(win){this.add.rectangle(W/2,H/2,W,H,0x07100a,.72).setDepth(20);this.add.rectangle(W/2,H/2,720,430,0x4d2917,.96).setStrokeStyle(8,0xd4934b).setDepth(21);this.add.text(W/2,H/2-110,win?'ПОБЕДА!':'ПОЧТИ ПОЛУЧИЛОСЬ!',{fontSize:'50px',fontStyle:'bold',color:'#ffe8a3',stroke:'#6b2d16',strokeThickness:8}).setOrigin(.5).setDepth(22);let b=this.add.image(W/2,H/2+90,'btn').setDisplaySize(320,112).setDepth(22).setInteractive({useHandCursor:true});this.add.text(W/2,H/2+90,win?'К КАРТЕ':'ЕЩЁ РАЗ',{fontSize:'34px',fontStyle:'bold',color:'#ffe9a8',stroke:'#5d2c15',strokeThickness:7}).setOrigin(.5).setDepth(23);b.on('pointerdown',()=>win?this.scene.start('Map'):this.scene.restart({n:this.no}))}
save(){let s={};try{s=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}let q=new Set(s.done||[]);q.add(this.no);s.done=[...q];localStorage.setItem(KEY,JSON.stringify(s))}
kingAnim(st){this.king.setTexture('king_'+(st==='celebrate'?'celebrate':st==='sad'?'sad':'idle'));this.tweens.killTweensOf(this.king);if(st==='celebrate')this.tweens.add({targets:this.king,y:'-=30',duration:220,yoyo:true,repeat:3,ease:'Back.out'});else if(st==='sad')this.tweens.add({targets:this.king,angle:-3,duration:650,yoyo:true,repeat:-1});else this.tweens.add({targets:this.king,y:'-=12',duration:1700,yoyo:true,repeat:-1,ease:'Sine.inOut'})}
toast(x){let t=this.add.text(W/2,990,x,{fontSize:'28px',fontStyle:'bold',color:'#fff4cf',stroke:'#4d2a16',strokeThickness:6}).setOrigin(.5).setDepth(15);this.tweens.add({targets:t,y:950,alpha:0,duration:1200,onComplete:()=>t.destroy()})}
uniq(a){let m=new Map();a.forEach(p=>{if(this.ins(p.r,p.c))m.set(p.r+','+p.c,p)});return[...m.values()]}
ins(r,c){return r>=0&&r<R&&c>=0&&c<C}}
new Phaser.Game({type:Phaser.AUTO,parent:'game',width:W,height:H,backgroundColor:'#10261a',scene:[Boot,Title,Map,Play],scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH,width:W,height:H},render:{antialias:true},audio:{disableWebAudio:false}});
})();
